language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t oldschoolweaver/react-test -f ./client/Dockerfile.dev ./client

#Runs the test here
script:
  - docker run -e CI=true oldschoolweaver/react-test npm test -- --coverage

after-success:
  - docker build -t oldschoolweaver/multi-client ./client
  - docker build -t oldschoolweaver/multi-nginx ./nginx
  - docker build -t oldschoolweaver/multi-server ./server
  - docker build -t oldschoolweaver/multi-worker ./worker

  #log in docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin 
  #Take the images to docker hub
  - docker push oldschoolweaver/multi-client
  - docker push oldschoolweaver/multi-nginx
  - docker push oldschoolweaver/multi-server
  - docker push oldschoolweaver/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-571650811739'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY