apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


#AccessModes: 
#ReadWriteOnce -> Can be used by a single node at a time
#ReadOnlyMany -> Multiple nodes can read from this
#ReadWriteMany -> Can b e read and written to by many nodes