apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432 #How other ports/services inside of our node will talk to us
      targetPort: 5432 # mapping between the expose port on the image and the clusterIP