apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379 #How other ports/services inside of our node will talk to us
      targetPort: 6379 # mapping between the expose port on the image and the clusterIP