#This is a file when we want combine all the config files into a single file. The '---' separates the different services. Best practices is to separate the files for Services.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000 #How other ports/services inside of our node will talk to us
      targetPort: 5000 # mapping between the expose port on the image and the clusterIP